from langchain_ollama import ChatOllama
from langchain_core.messages import (
    SystemMessage,
    HumanMessage,
    ToolMessage,
)

from tools import calculator, get_current_datetime


# -----------------------------
# Configuration
# -----------------------------

MODEL_NAME = "qwen3:4b"
MAX_ITERATIONS = 10


# -----------------------------
# Model
# -----------------------------

model = ChatOllama(
    model=MODEL_NAME,
    temperature=0,
)


# -----------------------------
# Tools
# -----------------------------

tools = [
    calculator,
    get_current_datetime,
]


# Create a dictionary so tools can be
# retrieved by the name generated by the LLM.
tools_by_name = {
    tool.name: tool
    for tool in tools
}


# Give the model access to the tool schemas.
model_with_tools = model.bind_tools(tools)


# -----------------------------
# System Prompt
# -----------------------------

system_message = SystemMessage(
    content="""
    You are Atlas, an AI research assistant.

    Answer questions accurately and clearly.

    You have access to tools.

    Use the calculator tool whenever arithmetic
    calculations are required.

    Use the get_current_datetime tool whenever
    the user asks for the current date or time.

    Do not invent tool results.
    """
)


# -----------------------------
# User Input
# -----------------------------

question = input("You: ")


messages = [
    system_message,
    HumanMessage(content=question),
]


# -----------------------------
# Agent Loop
# -----------------------------

for iteration in range(MAX_ITERATIONS):

    # Ask the model what to do next.
    response = model_with_tools.invoke(messages)

    # Save the model response to conversation state.
    messages.append(response)

    # ---------------------------------
    # No tool requested → final answer
    # ---------------------------------

    if not response.tool_calls:
        print(f"\nAtlas: {response.content}")
        break

    # ---------------------------------
    # Execute requested tools
    # ---------------------------------

    for tool_call in response.tool_calls:

        tool_name = tool_call["name"]
        tool_args = tool_call["args"]

        print(f"\n[Tool] Calling: {tool_name}")
        print(f"[Tool] Arguments: {tool_args}")

        # Make sure the requested tool exists.
        if tool_name not in tools_by_name:
            tool_result = (
                f"Error: Tool '{tool_name}' does not exist."
            )

        else:
            selected_tool = tools_by_name[tool_name]

            try:
                tool_result = selected_tool.invoke(
                    tool_args
                )

            except Exception as error:
                tool_result = (
                    f"Tool execution error: {error}"
                )

        print(f"[Tool] Result: {tool_result}")

        # Give the tool result back to the model.
        messages.append(
            ToolMessage(
                content=str(tool_result),
                tool_call_id=tool_call["id"],
            )
        )

else:
    print(
        "\nAtlas stopped because the maximum "
        "number of agent iterations was reached."
    )